### ISSUE TITLE
OUTPUT FILE error

### ISSUE THREAD

**Issue by luoxuye** [alexdobin/STAR#1074]
The first step was followed https://hbctraining.github.io/Intro-to-rnaseq-hpc-O2/lessons/03_alignment.html

STAR --runThreadN 28 \
--runMode genomeGenerate \
--genomeDir GRCh38 \
--genomeFastaFiles /project/data/GRCh38.p13.genome.fa \
--sjdbGTFfile /project/star/gencode.v35.annotation.gtf \
--sjdbOverhang 99

when I go second step:

STAR --genomeDir /project/star/GRCh38/ \
--runThreadN 28 \
--readFilesIn /project/star/SRR923803/SRR923803_1.fastq  /project/star/SRR923803/SRR923803_2.fastq \
--outFileNamePrefix /project/star/results/three \
--outSAMtype BAM SortedByCoordinate \
--outSAMunmapped Within \
--outSAMattributes Standard 

I got this error. 

BAMoutput.cpp:27:BAMoutput: exiting because of *OUTPUT FILE* error: could not create output file /project/star/results/three_STARtmp//BAMsort/20/16
SOLUTION: check that the path exists and you have write permission for this file. Also check ulimit -n and increase it to allow more open files.

Nov 08 20:25:01 ...... FATAL ERROR, exiting

But I do have permission.

My version is STAR-2.7.6a

**Comment by alexdobin** [comment]
Hi @luoxuye 

please try to increase the number of open files with
```ulimit -n 10000```
Alternatively, you can reduce the number of threads to ~12.

Cheers
Alex

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Dear Alex @alexdobin, I have a similar error.

````
Opening the file: /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs000452_PRJNA82747/CircRNA/STAR/SRR10841921/SRR10841921__STARtmp//Unmapped.out.mate1.thread17 ... ok
Opening the file: /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs000452_PRJNA82747/CircRNA/STAR/SRR10841921/SRR10841921__STARtmp//Unmapped.out.mate2.thread17 ... ok
Opening the file: /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs000452_PRJNA82747/CircRNA/STAR/SRR10841921/SRR10841921__STARtmp//Chimeric.out.junction.thread18 ... ok
Opening the file: /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs000452_PRJNA82747/CircRNA/STAR/SRR10841921/SRR10841921__STARtmp//Unmapped.out.mate1.thread18 ... ok
Opening the file: /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs000452_PRJNA82747/CircRNA/STAR/SRR10841921/SRR10841921__STARtmp//Unmapped.out.mate2.thread18 ... ok

BAMoutput.cpp:27:BAMoutput: exiting because of *OUTPUT FILE* error: could not create output file /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs000452_PRJNA82747/CircRNA/STAR/SRR10841921/SRR10841921__STARtmp//BAMsort/19/4
SOLUTION: check that the path exists and you have write permission for this file. Also check ulimit -n and increase it to allow more open files.

Jan 29 08:50:11 ...... FATAL ERROR, exiting
````
My code is :
    nohup STAR --chimSegmentMin 23 \
    --runThreadN 23 \
    --readFilesCommand zcat \
    --genomeDir ~/t12a/reference/hg38_ek12/STAR_index \
    -c --sjdbGTFfile ~/t12a/reference/hg38_ek12/gencode.v34.annotation.gtf \
    --outFileNamePrefix ${dir}/CircRNA/STAR/${i}/${i}_ \
    --outSAMorder Paired \
    --quantMode GeneCounts \
    --outSAMtype BAM SortedByCoordinate \
    --outReadsUnmapped Fastx \
    --outSAMattributes All \
    --readFilesIn ${dir}/clean/${i}_1_val_1.fq.gz ${dir}/clean/${i}_2_val_2.fq.gz
My star is version 2.7.1a.

**Comment by luoxuye** [comment]
Hi @jianguozhouzunyimedicaluniversity 

I fixed that issue.
as alexdobin said, you can reduce the number of threads to 12.

In your situation,  because you stopped at BAMsort/19/4, it means it only supports 18 or lower threads in your machine. 

You can try STAR --chimSegmentMin 18 or 17 or 16.

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Hi @luoxuye thx.
I tried it and set threads to 18.
however, still an error.
````
Created thread # 1
Created thread # 2
Created thread # 3
Created thread # 4
Created thread # 5
Created thread # 6
Created thread # 7
Created thread # 8
Created thread # 9
Created thread # 10
Created thread # 11
Created thread # 12
Starting to map file # 0
mate 1:   /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs000452_PRJNA82747/clean/SRR3083781_1_val_1.fq.gz
mate 2:   /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs000452_PRJNA82747/clean/SRR3083781_2_val_2.fq.gz
Created thread # 13
Created thread # 14
Created thread # 15
Created thread # 16
Created thread # 17
BAM sorting: 256928 mapped reads
BAM sorting bins genomic start loci:
1	0	28507377
2	0	28507380
3	0	28507380
4	0	28507380
5	0	28507380
6	0	28507380
7	0	28507380
8	0	28507380
9	0	28507380
10	0	28507381
11	0	28507381
12	0	28507381
13	0	28507381
14	0	28507381
15	0	28507386
16	0	28507386
17	0	28507389
18	0	28507391
19	0	28507396
20	0	28507397
21	0	28507403
22	0	28507407
23	0	28507410
24	0	28507410
25	0	28507415
26	0	28507420
27	0	28507422
28	0	28507424
29	0	28507427
30	0	28507429
31	0	28507435
32	0	28507435
33	0	28507437
34	0	28507440
35	0	28507445
36	0	28507447
37	0	28507448
38	0	28507448
39	0	28507452
40	0	28507455
41	0	28507458
42	0	28507470
43	0	28507479
44	0	28507480
45	0	28507483
46	0	28507486
47	0	28507487
48	0	28507489
Thread #16 end of input stream, nextChar=-1
Completed: thread #12
Completed: thread #16
Completed: thread #4
Completed: thread #14
Completed: thread #5
Completed: thread #6
Completed: thread #1
Completed: thread #9
Completed: thread #17
Completed: thread #3
Completed: thread #8
Completed: thread #7
Completed: thread #0
Joined thread # 1
Completed: thread #11
Completed: thread #10
Completed: thread #13
Completed: thread #2
Joined thread # 2
Joined thread # 3
Joined thread # 4
Joined thread # 5
Joined thread # 6
Joined thread # 7
Joined thread # 8
Joined thread # 9
Joined thread # 10
Joined thread # 11
Joined thread # 12
Joined thread # 13
Joined thread # 14
Completed: thread #15
Joined thread # 15
Joined thread # 16
Joined thread # 17
Jan 30 16:21:38 ..... started sorting BAM
Max memory needed for sorting = 37689307151

EXITING because of fatal ERROR: not enough memory for BAM sorting: 
SOLUTION: re-run STAR with at least --limitBAMsortRAM 38689307151
Jan 30 16:21:38 ...... FATAL ERROR, exiting
````

**Comment by luoxuye** [comment]
@jianguozhouzunyimedicaluniversity 
Sorry, I didn’t have this issue. You can Keep decreasing threads. 
It seems like you RAM is not enough. 
--limitBAMsortRAM 38689307151  = 35TB memory?
 I don’t think there are computers have 35TB memory. 
 Maybe you can create a new issue or search other’s issues.

**Comment by jianguozhouzunyimedicaluniversity** [comment]
> @jianguozhouzunyimedicaluniversity
> Sorry, I didn’t have this issue. My version is STAR-2.7.6a
> You can Keep decreasing threads.
> 
> Some suggestions
> 
> It seems like you RAM is not enough.
> --limitBAMsortRAM 38689307151 = 35TB memory? You can check how to use this option.
> I don’t think there are computers have 35TB memory. My computer is only 376GB memory.
> Maybe you can create a new issue or search other’s issues.

Hi @luoxuye, thanks for your help. 
I will ask @alexdobin to help me.
Best,
Jian-Guo

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Hi @luoxuye, I reduced the number of threads to 12, and worked.
Thx
