### ISSUE TITLE
using --outStd gives Segmentation fault

### ISSUE THREAD

**Issue by dariomel** [alexdobin/STAR#448]
I have compiled STAR on Ubuntu 14.04,
```bash
uname -a
Linux linux04 4.4.0-128-generic #154~14.04.1-Ubuntu SMP Fri May 25 14:58:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

STAR --version
STAR_2.6.0c
```

Running STAR as follows gives Segmentation fault:
```bash
STAR --outSAMmultNmax 4 --outFileNamePrefix ./star/ --runThreadN 4 --genomeDir gencode_19_GRCh37-ann --readFilesIn /dev/stdin --outFilterMismatchNmax 3 --outSAMunmapped Within --readMapNumber -1 --outFilterMultimapNmax -1 --alignSJoverhangMin 100 --alignSJDBoverhangMin 1 --alignEndsType EndToEnd --genomeLoad LoadAndRemove --outSAMtype SAM --outSAMmode NoQS --outStd SAM > temp.txt <<EOT
>0
TGTCCTCACTCCCCGAGTCCCTACTCTCCC
EOT
Segmentation fault (core dumped)
```

The problem disappears if I just remove `--outStd SAM > temp.txt` from the above command.

**Comment by alexdobin** [comment]
Hi Dario,

sorry for belayed reply. I could not reproduce this problem. Please send me the Log.out file.

Cheers
Alex

**Comment by dariomel** [comment]
here is the sub-directory created by the above command,
[star.zip](https://github.com/alexdobin/STAR/files/2237409/star.zip)

**Comment by alexdobin** [comment]
According to log files, the run completed fine.
Please try it again with a normal file instead of /dev/stdin or/and without --outStd SAM.
Also, you may want to run without the --genomeLoad option.

**Comment by dariomel** [comment]
below is what I get when I run STAR with GDB, with input from stdin or from a FASTA file that contains the same sequence passed to stdin. 
After each trial I quit gdb and clean up shared memory with ipcsrm if the program crashed.
Looks like SIGSEGV occurs when both options `--outStd` and `--genomeLoad` are given.
Note that I compiled STAR using gcc-7.1.0.

```
(gdb) run
Starting program: /mnt/share/apps/bio/star-2.6.0c/bin/STAR --outSAMmultNmax 4 --outFileNamePrefix ./star/ --runThreadN 4 --genomeDir /opt/archive/ref/align/star/gencode_19_GRCh37-ann --readFilesIn /dev/stdin --outFilterMismatchNmax 3 --outSAMunmapped Within --readMapNumber -1 --outFilterMultimapNmax -1 --alignSJoverhangMin 100 --alignSJDBoverhangMin 1 --alignEndsType EndToEnd --genomeLoad LoadAndRemove --outSAMtype SAM --outSAMmode NoQS --outStd SAM > temp.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ff8c9125700 (LWP 70698)]
[New Thread 0x7ff8c8924700 (LWP 70699)]
[New Thread 0x7ff8c8123700 (LWP 70700)]
>0
TGTCCTCACTCCCCGAGTCCCTACTCTCCC
[Thread 0x7ff8c8123700 (LWP 70700) exited]
[Thread 0x7ff8c8924700 (LWP 70699) exited]
[Thread 0x7ff8c9125700 (LWP 70698) exited]

Thread 1 "STAR" received signal SIGSEGV, Segmentation fault.
std::ostream::sentry::sentry (this=0x7fffffffb980, __os=...)
    at /mnt/home/administrator/tmp/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/ostream.tcc:51
51	      if (__os.tie() && __os.good())
(gdb) where
#0  std::ostream::sentry::sentry (this=0x7fffffffb980, __os=...)
    at /mnt/home/administrator/tmp/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/ostream.tcc:51
#1  0x00007ffff794a768 in std::__ostream_insert<char, std::char_traits<char> >
    (__out=..., 
    __s=0x4ee098 "No other jobs are attached to the shared memory segment, removing it.", __n=69)
    at /mnt/home/administrator/tmp/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/ostream_insert.h:82
#2  0x000000000040bb32 in SharedMemory::~SharedMemory() ()
#3  0x0000000000430681 in Genome::~Genome() ()
#4  0x0000000000407c0c in main ()
(gdb) quit


(gdb) run
Starting program: /mnt/share/apps/bio/star-2.6.0c/bin/STAR --outSAMmultNmax 4 --outFileNamePrefix ./star/ --runThreadN 4 --genomeDir /opt/archive/ref/align/star/gencode_19_GRCh37-ann --readFilesIn temp.fa --outFilterMismatchNmax 3 --outSAMunmapped Within --readMapNumber -1 --outFilterMultimapNmax -1 --alignSJoverhangMin 100 --alignSJDBoverhangMin 1 --alignEndsType EndToEnd --genomeLoad LoadAndRemove --outSAMtype SAM --outSAMmode NoQS --outStd SAM > temp.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ff8c9125700 (LWP 70751)]
[New Thread 0x7ff8c8924700 (LWP 70752)]
[New Thread 0x7ff8c8123700 (LWP 70753)]
[Thread 0x7ff8c8123700 (LWP 70753) exited]
[Thread 0x7ff8c8924700 (LWP 70752) exited]
[Thread 0x7ff8c9125700 (LWP 70751) exited]

Thread 1 "STAR" received signal SIGSEGV, Segmentation fault.
std::ostream::sentry::sentry (this=0x7fffffffb990, __os=...)
    at /mnt/home/administrator/tmp/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/ostream.tcc:51
51	      if (__os.tie() && __os.good())
(gdb) where
#0  std::ostream::sentry::sentry (this=0x7fffffffb990, __os=...)
    at /mnt/home/administrator/tmp/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/ostream.tcc:51
#1  0x00007ffff794a768 in std::__ostream_insert<char, std::char_traits<char> >
    (__out=..., 
    __s=0x4ee098 "No other jobs are attached to the shared memory segment, removing it.", __n=69)
    at /mnt/home/administrator/tmp/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/ostream_insert.h:82
#2  0x000000000040bb32 in SharedMemory::~SharedMemory() ()
#3  0x0000000000430681 in Genome::~Genome() ()
#4  0x0000000000407c0c in main ()
(gdb) quit


(gdb) run
Starting program: /mnt/share/apps/bio/star-2.6.0c/bin/STAR --outSAMmultNmax 4 --outFileNamePrefix ./star/ --runThreadN 4 --genomeDir /opt/archive/ref/align/star/gencode_19_GRCh37-ann --readFilesIn temp.fa --outFilterMismatchNmax 3 --outSAMunmapped Within --readMapNumber -1 --outFilterMultimapNmax -1 --alignSJoverhangMin 100 --alignSJDBoverhangMin 1 --alignEndsType EndToEnd --outSAMtype SAM --outSAMmode NoQS --outStd SAM > temp.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ff8c9124700 (LWP 70787)]
[New Thread 0x7ff8c8923700 (LWP 70788)]
[New Thread 0x7ff8c3fff700 (LWP 70789)]
[Thread 0x7ff8c3fff700 (LWP 70789) exited]
[Thread 0x7ff8c8923700 (LWP 70788) exited]
[Thread 0x7ff8c9124700 (LWP 70787) exited]
[Inferior 1 (process 70779) exited normally]
(gdb) quit


(gdb) run
Starting program: /mnt/share/apps/bio/star-2.6.0c/bin/STAR --outSAMmultNmax 4 --outFileNamePrefix ./star/ --runThreadN 4 --genomeDir /opt/archive/ref/align/star/gencode_19_GRCh37-ann --readFilesIn temp.fa --outFilterMismatchNmax 3 --outSAMunmapped Within --readMapNumber -1 --outFilterMultimapNmax -1 --alignSJoverhangMin 100 --alignSJDBoverhangMin 1 --alignEndsType EndToEnd --genomeLoad LoadAndRemove --outSAMtype SAM --outSAMmode NoQS
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Jul 27 15:55:02 ..... started STAR run
Jul 27 15:55:02 ..... loading genome
Jul 27 15:55:20 ..... started mapping
[New Thread 0x7ff8c9125700 (LWP 70839)]
[New Thread 0x7ff8c8924700 (LWP 70840)]
[New Thread 0x7ff8c3fff700 (LWP 70841)]
[Thread 0x7ff8c3fff700 (LWP 70841) exited]
[Thread 0x7ff8c8924700 (LWP 70840) exited]
[Thread 0x7ff8c9125700 (LWP 70839) exited]
Jul 27 15:55:21 ..... finished successfully
No other jobs are attached to the shared memory segment, removing it.
[Inferior 1 (process 70835) exited normally]
(gdb) quit


```

**Comment by alexdobin** [comment]
Hi Dario,

I think I have fixed the problem, please try the patch on GitHub [master](https://github.com/alexdobin/STAR/archive/master.zip).
Thanks a lot for your help with debugging!

Cheers
Alex

**Comment by dariomel** [comment]
Actually the bug is still there.

The problem is that the destructor of the local `SharedMemory` object is invoked upon exit from function `main`. That destructor attempts to write a message to the output stream pointed to by member `_err`, which was set by `Genome::genomeLoad` at `Genome.cpp:255` by calling `SharedMemory::SetErrorStream` with a pointer to member `logStdOutFile` of the `InOutStreams` instance pointed to by member `inOut` of the `Parameters` instance local to `main`. But pointer `_err` is stale when `~SharedMemory` is called, because the `InOutStreams` instance holding the pointed member `logStdOutFile` was destroyed by the statement `delete P.inOut` in function `main` at `STAR.cpp:488`.
A possible solution is to pass an `InOutStreams` pointer to the `Parameters` constructor and remove the existing statement `inOut = new InOutStreams` from that constructor,
```C++
Parameters::Parameters(InOutStreams* inOut) {//initalize parameters info
    this->inOut = inOut;
   // ...
}
```
then pass the expected pointer to the local `Parameters` instance in function `main`,
```C++
int main(int argInN, char* argIn[]) {
   // ...
    InOutStreams inOut;
    Parameters P(&inOut); //all parameters
    P.inputParameters(argInN, argIn);
   // ...
}
```
and finally remove the statement `delete P.inOut` at the end of function `main`.
Moreover, the above changes avoid the memory leak caused by the statement `P1.inOut = P.inOut` in function `Genome::genomeLoad` at `Genome.cpp:124`.

**Comment by alexdobin** [comment]
Hi Dario,

thanks a lot for the detailed analysis!
I do not get these seg-faults on my system, so it's hard for me to debug them.
As you pointed out, the underlying problem here is that the ~Genome needs to write to the logStdOut stream from the inOut class, and so it has to be called before the destruction of the inOut class.
I like your solution and will implement it at some point to get rid of the memory leak.
However, at the moment I would like to call the SharedMemory destructor explicitly before the inOut destructor. Ideally, I would need to write a more detailed destructor for the whole Genome class.

Please let me know if the new patch works or still has a problem.
Cheers
Alex
