### ISSUE TITLE
ReadAlignChunk_processChunks fails in 2.7.0c [not previous versions]

### ISSUE THREAD

**Issue by trebbiano** [alexdobin/STAR#568]
Hi Alex,
Just downloaded the new release and it failed on a standard mapping job. Repeated the same job with 2.6.1c with identical parameters and the mapping goes fine. Command line and parameters below.
`
jerry@ubuntu:~$ ~/STAR-2.7.0c/bin/Linux_x86_64/STAR --runThreadN 5 --genomeDir ~/Genomes/mm10_Ensembl_v87_STAR --sjdbGTFfile ~/Genomes/Ensembl/Mus_musculus.GRCm38.87.gtf --readFilesIn ~/file1.fastq.gz --readFilesCommand zcat --outFileNamePrefix ~/file1 --outSAMtype None --quantMode GeneCounts --sjdbOverhang 74`

Error message:
```
Feb 12 22:28:23 ..... started STAR run
Feb 12 22:28:23 ..... loading genome
Feb 12 22:29:03 ..... processing annotations GTF
Feb 12 22:29:23 ..... inserting junctions into the genome indices
Feb 12 22:33:44 ..... started mapping

ReadAlignChunk_processChunks.cpp:170:processChunks EXITING because of FATAL ERROR in input reads: unknown file format: the read ID should start with @ or > 
```

I also checked the integrity of the FASTQ file, it is fine, standard format and not truncated.

Best,
Jerry

**Comment by alexdobin** [comment]
Hi Jerry,

I think this is caused by using --sjdbGTFfile ann.gtf in the mapping step, there was a similar report 
[here](https://groups.google.com/d/msg/rna-star/-BZMRAA7NWU/bV9aLXQbIAAJ).
If you specified GTF file at the genome generation step, you do not need to specify it again at the mapping step.

Cheers
Alex

**Comment by alexdobin** [comment]
Hi Jerry,

have you re-generated the genome before running 2.7.0c?
I amde this a hard requirement, please test the GitHub master and let me know if it solves the problem.

Cheers
Alex

**Comment by trebbiano** [comment]
Hi Alex,
Thanks for the reply, the genome was generated using a previous version of STAR. I will generate a new copy and retry.

Thanks,
Jerry

**Comment by trebbiano** [comment]
I just regenerated the genome using 2.7.0c, re-run the code which gave the original error and the issue persists. New command line and error message:
```
~/STAR-2.7.0c/bin/Linux_x86_64/STAR --runThreadN 5 --genomeDir ~/mm10_Ensembl_v95_STAR --sjdbGTFfile ~/Mus_musculus.GRCm38.95.gtf --readFilesIn $file1 --readFilesCommand zcat --outFileNamePrefix $prefix1 --outSAMtype None --quantMode GeneCounts --sjdbOverhang 74

Feb 16 20:34:37 ..... started STAR run
Feb 16 20:34:37 ..... loading genome
Feb 16 20:37:35 ..... processing annotations GTF
Feb 16 20:38:01 ..... inserting junctions into the genome indices
Feb 16 20:42:24 ..... started mapping
./STAR_batch2.sh: line 26: 13538 Segmentation fault      (core dumped)
```

**Comment by alexdobin** [comment]
Hi Jerry,

could you please try the patch on GitHub [master](https://github.com/alexdobin/STAR/archive/master.zip) ?
There was another problem with the --quantMode GeneCounts option, which I fixed in this patch.

Cheers
Alex

**Comment by trebbiano** [comment]
I just regenerated the genome with 2.7.0d and tried to align the same reads as before (that previously mapped successfully with 2.6.1c) and the job still fails, with a traceback this time:
```
jerry@ubuntu:~$ ~/Downloads/STAR-2.7.0d/bin/Linux_x86_64/STAR --runThreadN 5 --genomeDir ~/mm10_Ensembl_v95_STAR --sjdbGTFfile ~/Mus_musculus.GRCm38.95.gtf --readFilesIn $file1 --readFilesCommand zcat --outFileNamePrefix $prefix1 --outSAMtype None --quantMode GeneCounts --sjdbOverhang 74
Feb 25 14:19:26 ..... started STAR run
Feb 25 14:19:26 ..... loading genome
Feb 25 14:21:46 ..... processing annotations GTF
Feb 25 14:22:07 ..... inserting junctions into the genome indices
Feb 25 14:26:33 ..... started mapping

ReadAlignChunk_processChunks.cpp:171:processChunks EXITING because of FATAL ERROR in input reads: unknown file format: the read ID should start with @ or > 
```

Traceback:
```
*** Error in `/home/jerry/Downloads/STAR-2.7.0d/bin/Linux_x86_64/STAR': double free or corruption (!prev): 0x0000000000ae87e0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fb8928677e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7fb89287037a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fb89287453c]
/lib/x86_64-linux-gnu/libc.so.6(fclose+0x103)[0x7fb89285d363]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSt12__basic_fileIcE5closeEv+0x3e)[0x7fb8935c819e]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSt13basic_filebufIcSt11char_traitsIcEE5closeEv+0xae)[0x7fb893607b4e]
/home/jerry/Downloads/STAR-2.7.0d/bin/Linux_x86_64/STAR[0x4411fa]
/home/jerry/Downloads/STAR-2.7.0d/bin/Linux_x86_64/STAR[0x48dc7f]
/home/jerry/Downloads/STAR-2.7.0d/bin/Linux_x86_64/STAR[0x462d0d]
/home/jerry/Downloads/STAR-2.7.0d/bin/Linux_x86_64/STAR[0x4a6569]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7fb892bc16ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fb8928f741d]
```

There is also a 'Memory map' with multiple lines, please let me know if that would be helpful to post.

Thanks,
Jerry

**Comment by alexdobin** [comment]
Hi Jerry,

could you try the [2.7.0e](https://github.com/alexdobin/STAR/releases/tag/2.7.0e) that I just released?
It's supposed to have fixed this problem. The 2.7.0d genome should work with this release.

Thanks!
Alex

**Comment by trebbiano** [comment]
That seems to have worked, thanks! 2.7.0e produced read counts that look correct, no errors this time. I'm closing the issue, thanks for the prompt responses,

Jerry
