### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by macmanes** [alexdobin/STAR#71]
with a `git clone` this AM (2 Sept)

`gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4`

```
make

cd source && make STAR
make[1]: Entering directory `/share/STAR/source'
Makefile:86: Depend.list: No such file or directory
echo alignSmithWaterman.cpp BAMbinSortByCoordinate.cpp BAMbinSortUnmapped.cpp BAMfunctions.cpp BAMoutput.cpp bamRemoveDuplicates.cpp binarySearch2.cpp blocksOverlap.cpp ErrorWarning.cpp extendAlign.cpp Genome.cpp genomeGenerate.cpp genomeParametersWrite.cpp GlobalVariables.cpp InOutStreams.cpp loadGTF.cpp mapThreadsSpawn.cpp outputSJ.cpp OutSJ.cpp PackedArray.cpp Parameters_closeReadsFiles.cpp Parameters.cpp Parameters_openReadsFiles.cpp Quantifications.cpp ReadAlign_alignBAM.cpp ReadAlign_assignAlignToWindow.cpp ReadAlign_chimericDetection.cpp ReadAlignChunk.cpp ReadAlignChunk_mapChunk.cpp ReadAlignChunk_processChunks.cpp ReadAlign.cpp ReadAlign_createExtendWindowsWithAlign.cpp ReadAlign_mapOneRead.cpp ReadAlign_maxMappableLength2strands.cpp ReadAlign_multMapSelect.cpp ReadAlign_oneRead.cpp ReadAlign_outputAlignments.cpp ReadAlign_outputTranscriptCIGARp.cpp ReadAlign_outputTranscriptSAM.cpp ReadAlign_outputTranscriptSJ.cpp ReadAlign_quantTranscriptome.cpp ReadAlign_stitchPieces.cpp ReadAlign_stitchWindowSeeds.cpp ReadAlign_storeAligns.cpp readLoad.cpp SequenceFuns.cpp serviceFuns.cpp SharedMemory.cpp signalFromBAM.cpp sjdbBuildIndex.cpp sjdbInsertJunctions.cpp sjdbLoadFromFiles.cpp sjdbLoadFromStream.cpp sjdbPrepare.cpp sjSplitAlign.cpp STAR.cpp Stats.cpp stitchAlignToTranscript.cpp stitchGapIndel.cpp stitchWindowAligns.cpp streamFuns.cpp stringSubstituteAll.cpp SuffixArrayFuns.cpp sysRemoveDir.cpp ThreadControl.cpp TimeFunctions.cpp Transcript_alignScore.cpp Transcript.cpp Transcriptome.cpp Transcriptome_geneCountsAddAlign.cpp Transcriptome_quantAlign.cpp bam_cat.c
alignSmithWaterman.cpp BAMbinSortByCoordinate.cpp BAMbinSortUnmapped.cpp BAMfunctions.cpp BAMoutput.cpp bamRemoveDuplicates.cpp binarySearch2.cpp blocksOverlap.cpp ErrorWarning.cpp extendAlign.cpp Genome.cpp genomeGenerate.cpp genomeParametersWrite.cpp GlobalVariables.cpp InOutStreams.cpp loadGTF.cpp mapThreadsSpawn.cpp outputSJ.cpp OutSJ.cpp PackedArray.cpp Parameters_closeReadsFiles.cpp Parameters.cpp Parameters_openReadsFiles.cpp Quantifications.cpp ReadAlign_alignBAM.cpp ReadAlign_assignAlignToWindow.cpp ReadAlign_chimericDetection.cpp ReadAlignChunk.cpp ReadAlignChunk_mapChunk.cpp ReadAlignChunk_processChunks.cpp ReadAlign.cpp ReadAlign_createExtendWindowsWithAlign.cpp ReadAlign_mapOneRead.cpp ReadAlign_maxMappableLength2strands.cpp ReadAlign_multMapSelect.cpp ReadAlign_oneRead.cpp ReadAlign_outputAlignments.cpp ReadAlign_outputTranscriptCIGARp.cpp ReadAlign_outputTranscriptSAM.cpp ReadAlign_outputTranscriptSJ.cpp ReadAlign_quantTranscriptome.cpp ReadAlign_stitchPieces.cpp ReadAlign_stitchWindowSeeds.cpp ReadAlign_storeAligns.cpp readLoad.cpp SequenceFuns.cpp serviceFuns.cpp SharedMemory.cpp signalFromBAM.cpp sjdbBuildIndex.cpp sjdbInsertJunctions.cpp sjdbLoadFromFiles.cpp sjdbLoadFromStream.cpp sjdbPrepare.cpp sjSplitAlign.cpp STAR.cpp Stats.cpp stitchAlignToTranscript.cpp stitchGapIndel.cpp stitchWindowAligns.cpp streamFuns.cpp stringSubstituteAll.cpp SuffixArrayFuns.cpp sysRemoveDir.cpp ThreadControl.cpp TimeFunctions.cpp Transcript_alignScore.cpp Transcript.cpp Transcriptome.cpp Transcriptome_geneCountsAddAlign.cpp Transcriptome_quantAlign.cpp bam_cat.c
/bin/rm -f ./Depend.list
g++ -pipe -std=c++0x -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Wed Sep 2 09:32:30 EDT 2015 :/share/STAR/source"' -MM alignSmithWaterman.cpp BAMbinSortByCoordinate.cpp BAMbinSortUnmapped.cpp BAMfunctions.cpp BAMoutput.cpp bamRemoveDuplicates.cpp binarySearch2.cpp blocksOverlap.cpp ErrorWarning.cpp extendAlign.cpp Genome.cpp genomeGenerate.cpp genomeParametersWrite.cpp GlobalVariables.cpp InOutStreams.cpp loadGTF.cpp mapThreadsSpawn.cpp outputSJ.cpp OutSJ.cpp PackedArray.cpp Parameters_closeReadsFiles.cpp Parameters.cpp Parameters_openReadsFiles.cpp Quantifications.cpp ReadAlign_alignBAM.cpp ReadAlign_assignAlignToWindow.cpp ReadAlign_chimericDetection.cpp ReadAlignChunk.cpp ReadAlignChunk_mapChunk.cpp ReadAlignChunk_processChunks.cpp ReadAlign.cpp ReadAlign_createExtendWindowsWithAlign.cpp ReadAlign_mapOneRead.cpp ReadAlign_maxMappableLength2strands.cpp ReadAlign_multMapSelect.cpp ReadAlign_oneRead.cpp ReadAlign_outputAlignments.cpp ReadAlign_outputTranscriptCIGARp.cpp ReadAlign_outputTranscriptSAM.cpp ReadAlign_outputTranscriptSJ.cpp ReadAlign_quantTranscriptome.cpp ReadAlign_stitchPieces.cpp ReadAlign_stitchWindowSeeds.cpp ReadAlign_storeAligns.cpp readLoad.cpp SequenceFuns.cpp serviceFuns.cpp SharedMemory.cpp signalFromBAM.cpp sjdbBuildIndex.cpp sjdbInsertJunctions.cpp sjdbLoadFromFiles.cpp sjdbLoadFromStream.cpp sjdbPrepare.cpp sjSplitAlign.cpp STAR.cpp Stats.cpp stitchAlignToTranscript.cpp stitchGapIndel.cpp stitchWindowAligns.cpp streamFuns.cpp stringSubstituteAll.cpp SuffixArrayFuns.cpp sysRemoveDir.cpp ThreadControl.cpp TimeFunctions.cpp Transcript_alignScore.cpp Transcript.cpp Transcriptome.cpp Transcriptome_geneCountsAddAlign.cpp Transcriptome_quantAlign.cpp bam_cat.c parametersDefault.xxd htslib >> Depend.list
g++: warning: parametersDefault.xxd: linker input file unused because linking not done
g++: warning: htslib: linker input file unused because linking not done
make[1]: Leaving directory `/share/STAR/source'
make[1]: Entering directory `/share/STAR/source'
g++ -c  -O3 -pipe -std=c++0x -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Wed Sep 2 09:32:34 EDT 2015 :/share/STAR/source"' SharedMemory.cpp
g++ -c  -O3 -pipe -std=c++0x -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Wed Sep 2 09:32:34 EDT 2015 :/share/STAR/source"' PackedArray.cpp
g++ -c  -O3 -pipe -std=c++0x -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Wed Sep 2 09:32:34 EDT 2015 :/share/STAR/source"' SuffixArrayFuns.cpp
SuffixArrayFuns.cpp:191:6: warning: unused parameter ‘dirR’ [-Wunused-parameter]
 uint suffixArraySearch(char** s2, uint S, uint N, char* G, PackedArray& SA, bool dirR, uint i1, uint i2, uint L, Parameters* P) {
      ^
SuffixArrayFuns.cpp: In function ‘long long unsigned int suffixArraySearch(char**, long long unsigned int, long long unsigned int, char*, PackedArray&, bool, long long unsigned int, long long unsigned int, long long unsigned int, Parameters*)’:
SuffixArrayFuns.cpp:264:9: warning: ‘compRes’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         if (compRes) { //move 1 to 3
         ^
g++ -c  -O3 -pipe -std=c++0x -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Wed Sep 2 09:32:34 EDT 2015 :/share/STAR/source"' STAR.cpp
g++ -c  -O3 -pipe -std=c++0x -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Wed Sep 2 09:32:34 EDT 2015 :/share/STAR/source"' Parameters.cpp
Parameters.cpp: In member function ‘void Parameters::inputParameters(int, char**)’:
Parameters.cpp:832:25: error: assigning to an array from an initializer list
     alignEndsType.ext[0]={false, false};
                         ^
Parameters.cpp:833:25: error: assigning to an array from an initializer list
     alignEndsType.ext[1]={false, false};
                         ^
Parameters.cpp:836:29: error: assigning to an array from an initializer list
         alignEndsType.ext[0]={true, true};
                             ^
Parameters.cpp:837:29: error: assigning to an array from an initializer list
         alignEndsType.ext[1]={true, true};
                             ^
Parameters.cpp:1036:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int ii=0; ii<chimFilter.size(); ii++)
                                       ^
Parameters.cpp:1054:46: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int ii=0; ii<readNameSeparator.size(); ii++)
                                              ^
make[1]: *** [Parameters.o] Error 1
make[1]: Leaving directory `/share/STAR/source'
make: *** [STAR] Error 2
```

**Comment by alexdobin** [comment]
Hi Matt,

I have pushed a fix on master, please try it out.

Cheers
Alex

**Comment by zyndagj** [comment]
Hello,

I still have the same compilation error using the most recent version of the code using gcc 4.9.1.

```shell
Parameters.cpp:839:29: error: assigning to an array from an initializer list
         alignEndsType.ext[0]={true, true};
                             ^
Parameters.cpp:840:29: error: assigning to an array from an initializer list
         alignEndsType.ext[1]={true, true};  
                             ^
```

**Comment by alexdobin** [comment]
Hi Greg,

sorry, forgot to fix another couple of lines. Please try it now.

Cheers
Alex

**Comment by macmanes** [comment]
this one works for me.
