### ISSUE TITLE
Raw barcode list does not reflect CB whitelisting

### ISSUE THREAD

**Issue by ColeWunderlich** [alexdobin/STAR#945]
For all of the quantification methods I have tested (`Gene` and `GeneFull`) the `barcodes.tsv` file in the `Solo.out/<quant_method>/raw/` folder does not reflect `CB` whitelisting.  Instead it is an exact copy of the 10x whitelist file.

Is this as intended?  I expected the `/raw/barcodes.tsv` file to be the list of `CR` that passed whitelist filtration, not a duplicate of the whitelist file.

It may also be worth mentioning that in the sample I have used for testing, only about 200k out of  the ~700K barcodes on the WL (10x V2 WL) match any of the observed CR barcodes from the sample.

**Comment by alexdobin** [comment]
Hi Cole

raw/barcodes.tsv is indeed the full copy of the whitelist. This is how CellRanger does it. I agree it would make sense to only list detected barcodes there.

The filtered barcodes are in the filtered/barcodes.tsv file.

Cheers
Alex

**Comment by ColeWunderlich** [comment]
Hey Alex,

That makes sense, I didn't know that was also how cell ranger handled it.

I still have some confusion over the different `CB` lists output from STARsolo though.

In one of my runs I have 290,976 unique `CB` tags in my bam file but there are only 253,113 entries in the `UMIperCellSorted.txt` file, for a total discrepancy of 37,863 missing  unique `CB` tag sequences.

I though this might be because low count `CB` sequences were being filtered out of the `UMIperCellSorted.txt` file, but when I looked there were many entries with only 1 count, so that doesn't seem to be the case.

The numbers in the `filtered` output did make sense though, I got 3,262 cells which is about what I would expect from the sample.  I'm still not sure what is causing the discrepancy between the number of unique `CB` tag sequences in the BAM file and the entries in `UMIperCellSorted.txt`.

Cole

**Comment by alexdobin** [comment]
Hi Cole,

the `UMIperCellSorted.txt` contains only the reads that align to genes, while BAM file also contains the reads that align to the genome, and - if you choose so - unaligned reads. The extra CBs you find in BAM should have no reads aligned to genes, i.e. no GX/GN tags.

Cheers
Alex

**Comment by ColeWunderlich** [comment]
Hey Alex,

Ah, that makes sense, thanks!

Is it sufficient to use `--outSAMunmapped` to get unaligned reads in the BAM file?  I was under the impression that only reads that mapped to locations with annotations would get `CB` corrected, or would unaligned reads get the corrected `CB` tags as well?

Also, I am currently quantifying with `GeneFull` and am not getting any `GX` or `GN` tags for some reason.  I wonder if this might be a similar issue to #907 .  (This was run with the `2.7.3a_2020-05-20` build, so maybe the issue got fixed with the #907 patch, I will test and report back)

**Comment by alexdobin** [comment]
Hi Cole,

for both unaligned reads and aligned unannotated reads, the CBs are not error-corrected. Again, this is CellRanger policy, which is probably not the most logical.

The GX/GN output issues with GeneFull should be solved now.

Cheers
Alex

**Comment by ColeWunderlich** [comment]
Hey Alex, sorry for the delayed reply.  

I recently did a solo run with the latest version (`2.7.5b`) and I am still not getting any `GX/N` tags when running in `GeneFull` mode.  I can only get `GX/N` tags when running in `Gene` mode.

**Comment by alexdobin** [comment]
Hi Cole,

indeed, it was not working - but should be fixed in 2.7.5c, please test it.
Thanks a lot for reporting the issue!

Cheers
Alex

**Comment by ColeWunderlich** [comment]
Hey Alex, I have tested it and can report that I am now getting `GN/X` tags when running with `GeneFull`! 

There are no `GX/N` tags anymore when running with `CB_samTagOut`, however, but from the commit history it looks like that was intentional.

With the latest patch `CB_samTagOut` now runs over twice as fast, which I am guessing is due to the fact that gene quantification is now no longer done.

Thanks for the patch!

**Comment by alexdobin** [comment]
Hi Cole,

thanks for testing it!

I will check the ```CB_samTagOut``` option, I do not see a reason not to output the GX/GN tags. Actually, I should output them even for non-solo runs.

Cheers
Alex

**Comment by deto** [comment]
The release notes for 2.7.6 note that GX/GN can be output for all runs, however I just tried a run of the form:

```
/home/ubuntu/programs/STAR-2.7.8a/bin/Linux_x86_64/STAR \
    --outSAMtype BAM SortedByCoordinate \
    --outSAMunmapped Within \
    --outSAMattributes NH HI AS nM GX GN \
    --genomeDir /home/ubuntu/References/GRCh38_STAR \
    --readFilesIn path/to/my/reads \
    --quantMode GeneCounts \
    --runThreadN 16
```

And the resulting BAM file does not contain these.  Is there an argument that I'm missing?
